//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ISpySoft.FeatureModelLanguage.DomainModel
{
	#region Using directives
	using System;
	#endregion
	
	public enum ActivitySort
	{
				Regular=0,
				SuperActivity=1,
		}
}
namespace ISpySoft.FeatureModelLanguage.DomainModel
{
	#region Using directives
	using System;
	#endregion
	
	public enum FeatureKind
	{
				Mandatory=0,
				Optional=1,
				FeatureSetFeature=2,
		}
}

