//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ISpySoft.SFSchemaLanguage.DomainModel
{
	#region Using directives
	using System;
	#endregion
	
	public enum ArtifactType
	{
				Asset=0,
				Tool=1,
				WorkProduct=2,
		}
}
namespace ISpySoft.SFSchemaLanguage.DomainModel
{
	#region Using directives
	using System;
	#endregion
	
	public enum ActivityHasArtifactDescription
	{
				uses=0,
				creates=1,
		}
}
namespace ISpySoft.SFSchemaLanguage.DomainModel
{
	#region Using directives
	using System;
	#endregion
	
	public enum MappingHasViewPointDescription
	{
				reads=0,
				writes=1,
		}
}

