
// do not use #pragma once - used by ctc compiler
#ifndef __GENERATEDCMD_H_
#define __GENERATEDCMD_H_

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This file contains generated default command definitions.
// Additional command definitions should be added to CustomCmd.ctc.
//

///////////////////////////////////////////////////////////////////////////////
// CTC command IDs - MUST be kept in sync with GeneratedCmd.cs

#define menuidContext		0x0100
#define menuidExplorer		0x0200

#define grpidContextMain	0x1030

#define cmdidViewExplorer	0x100

///////////////////////////////////////////////////////////////////////////////
// CTC macros

#define OI_NOID		guidOfficeIcon:msotcidNoIcon
#define DIS_DEF		DEFAULTDISABLED | DEFAULTINVISIBLE | DYNAMICVISIBILITY
#define VIS_DEF		COMMANDWELLONLY	

///////////////////////////////////////////////////////////////////////////////
// Menu definitions

#define GENERATED_MENUS \
	guidMenu:menuidContext, guidMenu:menuidContext,	0x0000,	CONTEXT|ALWAYSCREATE, "SFSchemaLanguage Designer Context Menu", "SFSchemaLanguage Context"; \
	guidMenu:menuidExplorer, guidMenu:menuidExplorer, 0x0000, CONTEXT|ALWAYSCREATE, "SFSchemaLanguage Explorer Context Menu", "SFSchemaLanguage Explorer"; \

///////////////////////////////////////////////////////////////////////////////
// Group definitions

#define GENERATED_GROUPS \
	guidMenu:grpidContextMain, guidMenu:grpidContextMain,	0x0010; \


///////////////////////////////////////////////////////////////////////////////
// Command definitions

#define GENERATED_BUTTONS \
	guidCmdSet:cmdidViewExplorer, guidSHLMainMenu:IDG_VS_WNDO_OTRWNDWS1, 0x0100,	OI_NOID, BUTTON, DIS_DEF, "SFSchemaLanguage Explorer";


///////////////////////////////////////////////////////////////////////////////
// Command placement definitions

#define GENERATED_CMDPLACEMENT \
	guidVSStd97:cmdidDelete, guidMenu:grpidContextMain, 0x0010; \
	guidMenu:grpidContextMain, guidMenu:menuidContext, 0x0010; \
	guidCommonModelingMenu:grpidExplorerMenuGroup, guidMenu:menuidExplorer, 0x0010; \
	guidSHLMainMenu:IDG_VS_CTXT_SOLUTION_PROPERTIES, guidMenu:menuidExplorer, 0x0020; \
	guidCommonModelingMenu:grpidValidateCommands, guidMenu:menuidExplorer, 0x0030; \
    guidCommonModelingMenu:grpidCompartmentShapeMenuGroup, guidMenu:menuidContext, 0x0008; \
	guidCommonModelingMenu:grpidValidateCommands, guidMenu:menuidContext, 0x0020; \
	guidCommonModelingMenu:grpidLayoutMenuGroup, guidMenu:menuidContext, 0x0030; \

///////////////////////////////////////////////////////////////////////////////
// Command visibility definitions

#define GENERATED_VISIBILITY \
	guidCmdSet:cmdidViewExplorer, guidEditor; \

///////////////////////////////////////////////////////////////////////////////
// CTC guids - MUST be kept in sync with GeneratedCmd.cs

#define guidPkg			{ 0x1042b62d, 0x5fd9, 0x474a, { 0xba, 0xb4, 0x7a, 0xf7, 0x42, 0x89, 0xee, 0x2a } }
#define guidCmdSet		{ 0x3ed3948f, 0xe952, 0x40e4, { 0xb0, 0xaf, 0xd7, 0xc0, 0x57, 0x23, 0xc8, 0xb2 } }
#define guidMenu		{ 0x2c243497, 0x9205, 0x46ea, { 0xbb, 0x6d, 0xd3, 0xc7, 0xad, 0xb4, 0x37, 0xba } }
#define guidEditor		{ 0x194f58e9, 0x3c67, 0x4a6e, { 0xb5, 0x4d, 0xab, 0x39, 0x04, 0xf0, 0x95, 0x70 } }

#endif // __GENERATEDCMD_H_