//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpySoft.SFSchemaLanguage.Designer
{
	#region Using directives
	using System;
	using System.Collections.Generic;
	using System.Diagnostics;
	using ISpySoft.SFSchemaLanguage.DomainModel ;
	using Microsoft.VisualStudio.Modeling;
	using Microsoft.VisualStudio.Modeling.Utilities;
	using System.Drawing;
	using System.Drawing.Drawing2D;
	using Microsoft.VisualStudio.Modeling.Diagrams;
	#endregion
	/// <summary>
	/// Partial class for connector with some overrides
	/// </summary>
	public partial class SchemaModelItemHasSchemaModelItemConnector : Connector
	{
		#region Static data
		private readonly static DecoratorDescription[] decoratorDescriptions = {
			new Microsoft.VisualStudio.Modeling.Utilities.TextConnectorDecoratorDescription("Label", ConnectorDecoratorPosition.TargetBottom, "DefaultLabelText")
    	       	    	    };
		private readonly static DecoratorMapping[] decoratorMappings = {
    		new Microsoft.VisualStudio.Modeling.Utilities.SimpleDecoratorMapping("Label", ISpySoft.SFSchemaLanguage.DomainModel.SchemaModelItemHasSchemaModelItem.DescriptionMetaAttributeGuidString),

        		           		};
		#endregion

		#region Decorators
		public override DecoratorDescription[] GetDecoratorDescriptions()
		{
			return SchemaModelItemHasSchemaModelItemConnector.decoratorDescriptions;
		}

		public override DecoratorMapping[] GetDecoratorMappings()
		{
			return SchemaModelItemHasSchemaModelItemConnector.decoratorMappings;
		}
		#endregion
	
		#region Visual settings
		
		protected override void InitializeInstanceResources()
		{
			base.InitializeInstanceResources();
			this.DecoratorTo = LinkDecorator.DecoratorEmptyArrow;
		}
		
        private System.Drawing.Color colorStorage = System.Drawing.Color.Black;

		/// <summary>
		/// ColorStorage
		/// </summary>
		/// <remarks>
		/// Color is a user-modifiable property hence it has backing store
		/// </remarks>
		[Variability(Variability.User)]
		protected override System.Drawing.Color ColorStorage
		{
			get 
			{ 
				return this.colorStorage;
			}
			set
			{
				this.colorStorage=value;
				}
		}
        private System.Drawing.Drawing2D.DashStyle dashStyleStorage = System.Drawing.Drawing2D.DashStyle.Solid;

		/// <summary>
		/// DashStyleStorage
		/// </summary>
		/// <remarks>
		/// DashStyle is a user-modifiable property hence it has backing store
		/// </remarks>
		[Variability(Variability.User)]
		protected override System.Drawing.Drawing2D.DashStyle DashStyleStorage
		{
			get 
			{ 
				return this.dashStyleStorage;
			}
			set
			{
				this.dashStyleStorage=value;
				}
		}
		#endregion

	}
}

