//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpySoft.SFSchemaLanguage.Designer.Diagram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Designer_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Designer_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISpySoft.SFSchemaLanguage.Designer.Diagram.Designer.Resource", typeof(Designer_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap activity {
            get {
                object obj = ResourceManager.GetObject("activity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string ActivityHasArtifactConnectorToolboxCaption {
            get {
                return ResourceManager.GetString("ActivityHasArtifactConnectorToolboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ActivityShapeToolboxCaption {
            get {
                return ResourceManager.GetString("ActivityShapeToolboxCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap artifact {
            get {
                object obj = ResourceManager.GetObject("artifact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        internal static string ArtifactShapeToolboxCaption {
            get {
                return ResourceManager.GetString("ArtifactShapeToolboxCaption", resourceCulture);
            }
        }
        
        internal static byte[] AssetIconFile {
            get {
                object obj = ResourceManager.GetObject("AssetIconFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connector {
            get {
                object obj = ResourceManager.GetObject("connector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Model.
        /// </summary>
        internal static string ExampleModel {
            get {
                return ResourceManager.GetString("ExampleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Factory Schema (*.sfschema)|*.sfschema.
        /// </summary>
        internal static string FormatList {
            get {
                return ResourceManager.GetString("FormatList", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mapping {
            get {
                object obj = ResourceManager.GetObject("mapping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping -&gt; ViewPoint.
        /// </summary>
        internal static string MappingHasViewPointConnectorToolboxCaption {
            get {
                return ResourceManager.GetString("MappingHasViewPointConnectorToolboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        internal static string MappingShapeToolboxCaption {
            get {
                return ResourceManager.GetString("MappingShapeToolboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFSchemaLanguage Explorer.
        /// </summary>
        internal static string ModelExplorerTitle {
            get {
                return ResourceManager.GetString("ModelExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That connection would create a loop.
        /// </summary>
        internal static string NoCycles {
            get {
                return ResourceManager.GetString("NoCycles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap role {
            get {
                object obj = ResourceManager.GetObject("role", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation cancelled..
        /// </summary>
        internal static string SaveOperationCancelled {
            get {
                return ResourceManager.GetString("SaveOperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were validation errors, continue save?.
        /// </summary>
        internal static string SaveValidationFailed {
            get {
                return ResourceManager.GetString("SaveValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stakeholders.
        /// </summary>
        internal static string StakeholderCompartmentCaption {
            get {
                return ResourceManager.GetString("StakeholderCompartmentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SF Schema Language.
        /// </summary>
        internal static string ToolboxTab {
            get {
                return ResourceManager.GetString("ToolboxTab", resourceCulture);
            }
        }
        
        internal static byte[] ToolIconFile {
            get {
                object obj = ResourceManager.GetObject("ToolIconFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewpoint {
            get {
                object obj = ResourceManager.GetObject("viewpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewPoint -&gt; Activity.
        /// </summary>
        internal static string ViewPointHasActivityConnectorToolboxCaption {
            get {
                return ResourceManager.GetString("ViewPointHasActivityConnectorToolboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewPoint -&gt; Asset/Tool.
        /// </summary>
        internal static string ViewPointHasArtifactConnectorToolboxCaption {
            get {
                return ResourceManager.GetString("ViewPointHasArtifactConnectorToolboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewPoint.
        /// </summary>
        internal static string ViewPointShapeToolboxCaption {
            get {
                return ResourceManager.GetString("ViewPointShapeToolboxCaption", resourceCulture);
            }
        }
        
        internal static byte[] WorkProductIconFile {
            get {
                object obj = ResourceManager.GetObject("WorkProductIconFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
