//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Constants.cs
using System;

namespace ISpySoft.FeatureModelLanguage.Designer
{
	internal static class Constants
	{
		public const string designerFileExtension = "featuremodel";
		public const string productName = "FeatureModelLanguageDesigner";
		public const string companyName = "CompanyName";
		public const string productVersion = "1.0.0.0";
	};
}