//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpySoft.FeatureModelLanguage.Designer.Shell
{
	#region Using directives

	using System;
	using System.Collections.Generic;
	using System.Text;
	using Microsoft.VisualStudio.EnterpriseTools.Shell;
	using Microsoft.VisualStudio.Modeling;
	using Microsoft.VisualStudio.Modeling.ArtifactMapper;

	#endregion

	internal sealed class DesignerCallbacks : DefaultDesignerCallbacks
	{
		public DesignerCallbacks( IServiceProvider serviceProvider) : base(serviceProvider, true /* report errors to task list */)
		{
		}

		public override bool AllowSynchronization(ModelElement element)
		{
			return true;
		}

		protected override int DesignerNameResourceId
		{
			get { return 106; }
		}

		protected override Guid PackageGuid
		{
			get { return typeof(FeatureModelLanguagePackage).GUID; }
		}
	}
}

