//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpySoft.FeatureModelLanguage.Designer
{
	#region Using directives

	using System;
	using System.Collections.Generic;
	using System.Text;
	using Microsoft.VisualStudio.EnterpriseTools.Shell;
	using Microsoft.VisualStudio.Modeling;
	using Microsoft.VisualStudio.Modeling.Diagrams;
	using ISpySoft.FeatureModelLanguage.Designer.Diagram;

	using SingleDiagramDocView = Microsoft.VisualStudio.Modeling.Utilities.SingleDiagramDocView;

	#endregion


	[CLSCompliant(false)]
	public class FeatureModelLanguageDocView : SingleDiagramDocView
	{
		public FeatureModelLanguageDocView(Microsoft.VisualStudio.EnterpriseTools.Shell.DocData docData, IServiceProvider serviceProvider) : base(docData, serviceProvider)
		{
		}

		protected override void Dispose(bool disposing)
		{
			try
			{
				// This is required by a Visual Studio bug and may not be required in later releases - flush undo stack when closing the DocView.
				if (this.DocData != null)
				{
					this.DocData.FlushUndoManager();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		protected override string DefaultToolboxTabName
		{
			get
			{
				return Designer_Resource.ToolboxTab;
			}
		}

		/// <summary>
		/// Context menu that should be displayed when the design surface is right-clicked on
		/// </summary>
		protected override System.ComponentModel.Design.CommandID ContextMenuId
		{
			get
			{
				if (this.contextMenuId == null)
				{
					this.contextMenuId = new System.ComponentModel.Design.CommandID(GuidList.guidFeatureModelLanguageMenu, PackageMenuIdList.menuIdContext);
				}
				return this.contextMenuId;
			}
		}

		private System.ComponentModel.Design.CommandID contextMenuId;
	}
}

