//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// MUST match GeneratedCmd.h
using System;

namespace ISpySoft.FeatureModelLanguage.Designer
{
    internal static class PackageCommandIdList
    {
        public const uint cmdIdViewExplorer = 0x100;
    }

    internal static class PackageMenuIdList
    {
		public const int menuIdContext = 0x0100;
		public const int menuIdExplorer = 0x0200;
	}
}

namespace ISpySoft.FeatureModelLanguage.Designer
{
	class GuidList
	{
		private GuidList(){}

		public const string guidFeatureModelLanguagePkgString = "775af6f2-e57f-43a6-847b-c77893efd982";
		public static readonly Guid guidFeatureModelLanguagePkg = new Guid(guidFeatureModelLanguagePkgString);
		public const string guidFeatureModelLanguageCmdSetString = "c93ab5fa-3aff-457d-b166-aca3c291adad";
		public static readonly Guid guidFeatureModelLanguageCmdSet = new Guid(guidFeatureModelLanguageCmdSetString);
		public const string guidFeatureModelLanguageMenuString = "2f747dc0-bb5b-4c7f-8997-9062724c5118";
		public static readonly Guid guidFeatureModelLanguageMenu = new Guid(guidFeatureModelLanguageMenuString);
		public const string guidEditorFactoryString = "a481ee5a-7a23-4057-8621-2b02a3f9cbbf";
		public static readonly Guid guidEditorFactory = new Guid(guidEditorFactoryString);
		public const string guidModelExplorerToolWindowString = "6f2b7518-f4e1-425c-b04d-d90a6f7138d3";
		public static readonly Guid guidModelExplorerToolWindow = new Guid(guidModelExplorerToolWindowString);
	};
}
