//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpySoft.FeatureModelLanguage.Designer
{
	#region Using directives
	using System;
	using System.Collections.Generic;
	using System.Diagnostics;
	using ISpySoft.FeatureModelLanguage.DomainModel ;
	using Microsoft.VisualStudio.Modeling;
	using Microsoft.VisualStudio.Modeling.Utilities;
	using System.Drawing;
	using System.Drawing.Drawing2D;
	using Microsoft.VisualStudio.Modeling.Diagrams;
	#endregion
	/// <summary>
	/// Partial class for connector with some overrides
	/// </summary>
	public partial class RelationshipFeatureConnector : Connector
	{
		#region Static data
		private readonly static DecoratorDescription[] decoratorDescriptions = {
    	       	    	    };
		private readonly static DecoratorMapping[] decoratorMappings = {
        		           		};
		#endregion

		#region Decorators
		public override DecoratorDescription[] GetDecoratorDescriptions()
		{
			return RelationshipFeatureConnector.decoratorDescriptions;
		}

		public override DecoratorMapping[] GetDecoratorMappings()
		{
			return RelationshipFeatureConnector.decoratorMappings;
		}
		#endregion
	
		#region Visual settings
		
		
        private System.Drawing.Color colorStorage = System.Drawing.Color.Black;

		/// <summary>
		/// ColorStorage
		/// </summary>
		/// <remarks>
		/// Color is a user-modifiable property hence it has backing store
		/// </remarks>
		[Variability(Variability.User)]
		protected override System.Drawing.Color ColorStorage
		{
			get 
			{ 
				return this.colorStorage;
			}
			set
			{
				this.colorStorage=value;
				}
		}
        private System.Drawing.Drawing2D.DashStyle dashStyleStorage = System.Drawing.Drawing2D.DashStyle.Solid;

		/// <summary>
		/// DashStyleStorage
		/// </summary>
		/// <remarks>
		/// DashStyle is a user-modifiable property hence it has backing store
		/// </remarks>
		[Variability(Variability.User)]
		protected override System.Drawing.Drawing2D.DashStyle DashStyleStorage
		{
			get 
			{ 
				return this.dashStyleStorage;
			}
			set
			{
				this.dashStyleStorage=value;
				}
		}
		#endregion

	}
	/// <summary>
	/// Partial class for connector with some overrides
	/// </summary>
	public partial class RelationshipFeatureSetConnector : Connector
	{
		#region Static data
		private readonly static DecoratorDescription[] decoratorDescriptions = {
    	       	    	    };
		private readonly static DecoratorMapping[] decoratorMappings = {
        		           		};
		#endregion

		#region Decorators
		public override DecoratorDescription[] GetDecoratorDescriptions()
		{
			return RelationshipFeatureSetConnector.decoratorDescriptions;
		}

		public override DecoratorMapping[] GetDecoratorMappings()
		{
			return RelationshipFeatureSetConnector.decoratorMappings;
		}
		#endregion
	
		#region Visual settings
		
		
        private System.Drawing.Color colorStorage = System.Drawing.Color.Black;

		/// <summary>
		/// ColorStorage
		/// </summary>
		/// <remarks>
		/// Color is a user-modifiable property hence it has backing store
		/// </remarks>
		[Variability(Variability.User)]
		protected override System.Drawing.Color ColorStorage
		{
			get 
			{ 
				return this.colorStorage;
			}
			set
			{
				this.colorStorage=value;
				}
		}
		/// <summary>
		/// DashStyleStorage
		/// </summary>
		/// <remarks>
		/// DashStyle is a fixed property hence it has no backing store
		/// </remarks>
		[Variability(Variability.Fixed)]
		protected override System.Drawing.Drawing2D.DashStyle DashStyleStorage
		{
			get 
			{ 
				return System.Drawing.Drawing2D.DashStyle.Solid;
			}
			set
			{
				throw new InvalidOperationException(); 
				}
		}
		#endregion

	}
}

