//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpySoft.FeatureModelLanguage.Designer.Diagram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Designer_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Designer_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISpySoft.FeatureModelLanguage.Designer.Diagram.Designer.Resource", typeof(Designer_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Feature {
            get {
                object obj = ResourceManager.GetObject("Feature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string FeatureCaption {
            get {
                return ResourceManager.GetString("FeatureCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FeatureConnector {
            get {
                object obj = ResourceManager.GetObject("FeatureConnector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Connector.
        /// </summary>
        internal static string FeatureConnectorCaption {
            get {
                return ResourceManager.GetString("FeatureConnectorCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FeatureSet {
            get {
                object obj = ResourceManager.GetObject("FeatureSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Set.
        /// </summary>
        internal static string FeatureSetCaption {
            get {
                return ResourceManager.GetString("FeatureSetCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FeatureSetConnector {
            get {
                object obj = ResourceManager.GetObject("FeatureSetConnector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Set Connector.
        /// </summary>
        internal static string FeatureSetConnectorCaption {
            get {
                return ResourceManager.GetString("FeatureSetConnectorCaption", resourceCulture);
            }
        }
        
        internal static byte[] FeatureSetImage {
            get {
                object obj = ResourceManager.GetObject("FeatureSetImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Model (*.featuremodel)|*.featuremodel.
        /// </summary>
        internal static string FormatList {
            get {
                return ResourceManager.GetString("FormatList", resourceCulture);
            }
        }
        
        internal static byte[] MandatoryIconFile {
            get {
                object obj = ResourceManager.GetObject("MandatoryIconFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Model Explorer.
        /// </summary>
        internal static string ModelExplorerTitle {
            get {
                return ResourceManager.GetString("ModelExplorerTitle", resourceCulture);
            }
        }
        
        internal static byte[] OptionalIconFile {
            get {
                object obj = ResourceManager.GetObject("OptionalIconFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RootFeature {
            get {
                object obj = ResourceManager.GetObject("RootFeature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Feature.
        /// </summary>
        internal static string RootFeatureCaption {
            get {
                return ResourceManager.GetString("RootFeatureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation cancelled..
        /// </summary>
        internal static string SaveOperationCancelled {
            get {
                return ResourceManager.GetString("SaveOperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were validation errors, continue save?.
        /// </summary>
        internal static string SaveValidationFailed {
            get {
                return ResourceManager.GetString("SaveValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Model.
        /// </summary>
        internal static string ToolboxTab {
            get {
                return ResourceManager.GetString("ToolboxTab", resourceCulture);
            }
        }
    }
}
