//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	
namespace ISpySoft.FeatureModelLanguage.Designer
{
	#region Using directives

	using System;
	using System.Collections.Generic;
	using System.Text;
	using Microsoft.VisualStudio.Modeling.Utilities;
	using Microsoft.VisualStudio.Modeling;
	using Microsoft.VisualStudio.Modeling.Diagrams;

	#endregion

	public partial class FeatureModelLanguageDiagram
	{
		#region Constants
		public const string DiagramFilterString = "FeatureModelLanguageDiagram";
		#endregion

		#region Fields
		/// <summary>
		/// Connect action for RelationshipFeatureConnector
		/// </summary>
		[NonSerialized]
		private RelationshipFeatureConnectorConnectAction relationshipfeatureconnectorConnectAction;

		/// <summary>
		/// Connect action for RelationshipFeatureSetConnector
		/// </summary>
		[NonSerialized]
		private RelationshipFeatureSetConnectorConnectAction relationshipfeaturesetconnectorConnectAction;


		#endregion
	
		#region View Fixup

		/// <summary>
		/// Check whether shapes should be added for a particular element
		/// </summary>
		/// <remarks>
		/// Base class provides test when a drag-drop is performed.  This override provides the
		/// test for when reverse-engineering (load) happens.
		/// </remarks>
		/// <param name="element">The element to test</param>
		/// <returns>Whether to add a shape</returns>
		protected override bool ShouldAddShapeForElement(Microsoft.VisualStudio.Modeling.ModelElement element)
		{
			bool addShape = false;

			// Make a list of all elements mapped from the shape / connector maps
						if (element is ISpySoft.FeatureModelLanguage.DomainModel.FeatureSet) addShape = true;
			if (element is ISpySoft.FeatureModelLanguage.DomainModel.Feature) addShape = true;
			if (element is ISpySoft.FeatureModelLanguage.DomainModel.RootFeature) addShape = true;
 			if (element is ISpySoft.FeatureModelLanguage.DomainModel.RelationshipFeature) addShape = true;
 			if (element is ISpySoft.FeatureModelLanguage.DomainModel.RelationshipFeatureSet) addShape = true;
			return addShape;
		}
	
		/// <summary>
		/// Override to configure shapes when they are added to the diagram
		/// </summary>
		/// <param name="child"></param>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		protected override void OnChildConfiguring(ShapeElement child)
		{
			base.OnChildConfiguring(child);
			// When a RelationshipFeatureConnector is created, configure it to be connected up to the right 
			// source and target shapes
			RelationshipFeatureConnector relationshipfeatureconnector = child as RelationshipFeatureConnector;
			if (relationshipfeatureconnector != null && relationshipfeatureconnector.ModelElement != null)
			{
				ISpySoft.FeatureModelLanguage.DomainModel.RelationshipFeature relationship = relationshipfeatureconnector.ModelElement as ISpySoft.FeatureModelLanguage.DomainModel.RelationshipFeature;
				if (relationship != null)
				{
				
					if (relationshipfeatureconnector.FromShape == null)
					{
						Shape sourceShape = this.FindShape(relationship.TransitionFrom);
						Shape targetShape = this.FindShape(relationship.TransitionTo);
						if (sourceShape != null && targetShape != null)
						{
							relationshipfeatureconnector.Connect(sourceShape, targetShape);
						}
					}
				
				}
			}
			// When a RelationshipFeatureSetConnector is created, configure it to be connected up to the right 
			// source and target shapes
			RelationshipFeatureSetConnector relationshipfeaturesetconnector = child as RelationshipFeatureSetConnector;
			if (relationshipfeaturesetconnector != null && relationshipfeaturesetconnector.ModelElement != null)
			{
				ISpySoft.FeatureModelLanguage.DomainModel.RelationshipFeatureSet relationship = relationshipfeaturesetconnector.ModelElement as ISpySoft.FeatureModelLanguage.DomainModel.RelationshipFeatureSet;
				if (relationship != null)
				{
				
					if (relationshipfeaturesetconnector.FromShape == null)
					{
						Shape sourceShape = this.FindShape(relationship.ObjectTransitionFrom);
						Shape targetShape = this.FindShape(relationship.ObjectTransitionTo);
						if (sourceShape != null && targetShape != null)
						{
							relationshipfeaturesetconnector.Connect(sourceShape, targetShape);
						}
					}
				
				}
			}
		}
	
		#endregion

		#region Mouse Actions
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new ArgumentNullException("pointArgs");
			
			MouseAction action = null;

			if (ActiveDiagramView != null)
			{
				if (ActiveDiagramView.SelectedToolboxItemSupportsFilterString(EditorFactory.RelationshipFeatureConnectorFilterString))
				{
					action = this.RelationshipFeatureConnectorConnectAction;
				}
				if (ActiveDiagramView.SelectedToolboxItemSupportsFilterString(EditorFactory.RelationshipFeatureSetConnectorFilterString))
				{
					action = this.RelationshipFeatureSetConnectorConnectAction;
				}
			}

			if (pointArgs.DiagramClientView.ActiveMouseAction != action)
			{
				pointArgs.DiagramClientView.ActiveMouseAction = action;
			}
		}

		/// <summary>
		/// Gets the RelationshipFeatureConnector connection tool mouse action for this Diagram.
		/// </summary>
		/// <remarks>
		/// This connection tool supports dragging as well as clicking to create a connection.
		/// </remarks>
		private RelationshipFeatureConnectorConnectAction RelationshipFeatureConnectorConnectAction
		{
			get
			{
				if (this.relationshipfeatureconnectorConnectAction == null)
				{
					this.relationshipfeatureconnectorConnectAction = new RelationshipFeatureConnectorConnectAction(this, true);
					this.relationshipfeatureconnectorConnectAction.MouseActionDeactivated += new MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
				}

				return this.relationshipfeatureconnectorConnectAction;
			}
		}
		/// <summary>
		/// Gets the RelationshipFeatureSetConnector connection tool mouse action for this Diagram.
		/// </summary>
		/// <remarks>
		/// This connection tool supports dragging as well as clicking to create a connection.
		/// </remarks>
		private RelationshipFeatureSetConnectorConnectAction RelationshipFeatureSetConnectorConnectAction
		{
			get
			{
				if (this.relationshipfeaturesetconnectorConnectAction == null)
				{
					this.relationshipfeaturesetconnectorConnectAction = new RelationshipFeatureSetConnectorConnectAction(this, true);
					this.relationshipfeaturesetconnectorConnectAction.MouseActionDeactivated += new MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
				}

				return this.relationshipfeaturesetconnectorConnectAction;
			}
		}
		#endregion
	}
}

