
// do not use #pragma once - used by ctc compiler
#ifndef __GENERATEDCMD_H_
#define __GENERATEDCMD_H_

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This file contains generated default command definitions.
// Additional command definitions should be added to CustomCmd.ctc.
//

///////////////////////////////////////////////////////////////////////////////
// CTC command IDs - MUST be kept in sync with GeneratedCmd.cs

#define menuidContext		0x0100
#define menuidExplorer		0x0200

#define grpidContextMain	0x1030

#define cmdidViewExplorer	0x100

///////////////////////////////////////////////////////////////////////////////
// CTC macros

#define OI_NOID		guidOfficeIcon:msotcidNoIcon
#define DIS_DEF		DEFAULTDISABLED | DEFAULTINVISIBLE | DYNAMICVISIBILITY
#define VIS_DEF		COMMANDWELLONLY	

///////////////////////////////////////////////////////////////////////////////
// Menu definitions

#define GENERATED_MENUS \
	guidMenu:menuidContext, guidMenu:menuidContext,	0x0000,	CONTEXT|ALWAYSCREATE, "FeatureModelLanguage Designer Context Menu", "FeatureModelLanguage Context"; \
	guidMenu:menuidExplorer, guidMenu:menuidExplorer, 0x0000, CONTEXT|ALWAYSCREATE, "FeatureModelLanguage Explorer Context Menu", "FeatureModelLanguage Explorer"; \

///////////////////////////////////////////////////////////////////////////////
// Group definitions

#define GENERATED_GROUPS \
	guidMenu:grpidContextMain, guidMenu:grpidContextMain,	0x0010; \


///////////////////////////////////////////////////////////////////////////////
// Command definitions

#define GENERATED_BUTTONS \
	guidCmdSet:cmdidViewExplorer, guidSHLMainMenu:IDG_VS_WNDO_OTRWNDWS1, 0x0100,	OI_NOID, BUTTON, DIS_DEF, "FeatureModelLanguage Explorer";


///////////////////////////////////////////////////////////////////////////////
// Command placement definitions

#define GENERATED_CMDPLACEMENT \
	guidVSStd97:cmdidDelete, guidMenu:grpidContextMain, 0x0010; \
	guidMenu:grpidContextMain, guidMenu:menuidContext, 0x0010; \
	guidCommonModelingMenu:grpidExplorerMenuGroup, guidMenu:menuidExplorer, 0x0010; \
	guidSHLMainMenu:IDG_VS_CTXT_SOLUTION_PROPERTIES, guidMenu:menuidExplorer, 0x0020; \
	guidCommonModelingMenu:grpidValidateCommands, guidMenu:menuidExplorer, 0x0030; \
    guidCommonModelingMenu:grpidCompartmentShapeMenuGroup, guidMenu:menuidContext, 0x0008; \
	guidCommonModelingMenu:grpidValidateCommands, guidMenu:menuidContext, 0x0020; \
	guidCommonModelingMenu:grpidLayoutMenuGroup, guidMenu:menuidContext, 0x0030; \

///////////////////////////////////////////////////////////////////////////////
// Command visibility definitions

#define GENERATED_VISIBILITY \
	guidCmdSet:cmdidViewExplorer, guidEditor; \

///////////////////////////////////////////////////////////////////////////////
// CTC guids - MUST be kept in sync with GeneratedCmd.cs

#define guidPkg			{ 0x775af6f2, 0xe57f, 0x43a6, { 0x84, 0x7b, 0xc7, 0x78, 0x93, 0xef, 0xd9, 0x82 } }
#define guidCmdSet		{ 0xc93ab5fa, 0x3aff, 0x457d, { 0xb1, 0x66, 0xac, 0xa3, 0xc2, 0x91, 0xad, 0xad } }
#define guidMenu		{ 0x2f747dc0, 0xbb5b, 0x4c7f, { 0x89, 0x97, 0x90, 0x62, 0x72, 0x4c, 0x51, 0x18 } }
#define guidEditor		{ 0xa481ee5a, 0x7a23, 0x4057, { 0x86, 0x21, 0x2b, 0x02, 0xa3, 0xf9, 0xcb, 0xbf } }

#endif // __GENERATEDCMD_H_