//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Constants.cs
using System;

namespace ISpySoft.SFSchemaLanguage.Designer
{
	internal static class Constants
	{
		public const string designerFileExtension = "sfschema";
		public const string productName = "Software Factory Schema DSL";
		public const string companyName = "Lenz & Wienands";
		public const string productVersion = "1.0.0.0";
	};
}