//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// MUST match GeneratedCmd.h
using System;

namespace ISpySoft.SFSchemaLanguage.Designer
{
    internal static class PackageCommandIdList
    {
        public const uint cmdIdViewExplorer = 0x100;
    }

    internal static class PackageMenuIdList
    {
		public const int menuIdContext = 0x0100;
		public const int menuIdExplorer = 0x0200;
	}
}

namespace ISpySoft.SFSchemaLanguage.Designer
{
	class GuidList
	{
		private GuidList(){}

		public const string guidSFSchemaLanguagePkgString = "1042b62d-5fd9-474a-bab4-7af74289ee2a";
		public static readonly Guid guidSFSchemaLanguagePkg = new Guid(guidSFSchemaLanguagePkgString);
		public const string guidSFSchemaLanguageCmdSetString = "3ed3948f-e952-40e4-b0af-d7c05723c8b2";
		public static readonly Guid guidSFSchemaLanguageCmdSet = new Guid(guidSFSchemaLanguageCmdSetString);
		public const string guidSFSchemaLanguageMenuString = "2c243497-9205-46ea-bb6d-d3c7adb437ba";
		public static readonly Guid guidSFSchemaLanguageMenu = new Guid(guidSFSchemaLanguageMenuString);
		public const string guidEditorFactoryString = "194f58e9-3c67-4a6e-b54d-ab3904f09570";
		public static readonly Guid guidEditorFactory = new Guid(guidEditorFactoryString);
		public const string guidModelExplorerToolWindowString = "6d42727a-dae1-43b1-894c-ef0860cd97eb";
		public static readonly Guid guidModelExplorerToolWindow = new Guid(guidModelExplorerToolWindowString);
	};
}
