//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
namespace ISpySoft.SFSchemaLanguage.Designer.Shell
{
	using System;
	using Microsoft.VisualStudio.Modeling;
	using Microsoft.VisualStudio.Modeling.Utilities;

	internal sealed class SFSchemaLanguagePropertyDescriptionRedirector : Microsoft.VisualStudio.Modeling.Utilities.PropertyDescriptionRedirector
	{
		public SFSchemaLanguagePropertyDescriptionRedirector(IServiceProvider serviceProvider, Store store)
			: base(serviceProvider, store)
		{
		}

		protected override PropertyDescriptorEntry[] GetPropertyDescriptorTable()
		{
			return null;
		}

		protected override ShapeAttributeVariabilityRecord[] GetShapeVariabilityTable()
		{
			return null;
		}
	}
}

